cargo-features = ["edition2024"]

[package]
name = "example_proc_macro"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
tracing-proc-macros-ink = { path = "../.." }
tracing = "0.1"
tracing-subscriber = "0.3"
